
services:
  api:
    build: .
    container_name: my-fastapi
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:16
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
